### ISSUE TITLE
No way to lift lockdown or fully uninstall app

### ISSUE THREAD

**Issue by petiteoffense** [brnhrd/DueProcess#3]
I ran into a couple of critical problems while testing this app. After putting the work profile into lockdown mode, I simply could not figure out how to lift the lockdown. The instruction given when setting up the app is a little vague, indicating to turn the work profile off and on and wait for a couple seconds before entering the unlock gesture. I’m not 100% certain what’s meant by turning the work profile off and on, but I figured it meant pulling down the notification bar and toggling the ‘Work Mode’ button. I tried this several times. I saw no indication of any change after a couple of seconds, but I suppose this is to be expected as the instructions indicated the lockscreen would be an invisible overlay. So I tried drawing the pattern. Nothing happened, and the apps that I had included in the lockdown remained invisible. I tried this many times, even locking the device in-between toggling work mode, but it never worked.

I couldn’t see any other way to try to lift the lockdown, so I uninstalled the app (which took 2 attempts). Though I was apparently able to remove the app, now when I try to re-install it I am given the message “Action not allowed—you do not have permission to perform this action. Contact your organization’s IT administrator for more information”. And neither can I change the settings to re-enable installation of apps from unknown sources. So clearly some element of the app is still present with admin control of the device, but I have absolutely no way to access the app or its settings.

I'm really worried I've irrevocably messed up my device. It's possible that the app is malicious, though I think this is unlikely given its provenance. I think it is more likely that either I've misunderstood how to lift the lockdown and that the app could just use a bit more clarity in the instructions or that there is some serious compatibility issue with newer versions of Android since this hasn't been updated in some time. Regardless, any help or updates would be greatly appreciated.

**Comment by brnhrd** [comment]
We troubleshot this issue in a private conversation, therefore closing this for now.

To lift the lockdown, make sure to be on your homescreen (no notification shade, no open menus) after enabling the work profile. This will allow you to enter the pattern on the invisible lockscreen. Also, make sure that the app (the work profile instance) is allowed to draw over other apps.

For anyone else having issues uninstalling the application: You can always delete the work profile from the system account settings. This will fully remove the profile and the applications inside of it.
